services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    command: >
      bash -c "
        bundle install &&
        gem install foreman &&
        bundle exec rails db:prepare &&
        ./bin/dev
      "
    stdin_open: true
    tty: true

volumes:
  bundle_cache: