services:
  - type: web
    name: murmur
    runtime: ruby
    env: ruby
    region: oregon
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: postgresql://murmur_o49g_user:ZbY7ZKl5HBPtG0Uk0FLJ3TqkNOR6SEuk@dpg-d3hk1g0gjchc73aichrg-a.oregon-postgres.render.com:5432/murmur_o49g
      - key: RAILS_MASTER_KEY
        value: 75a2235a478bd7108f500da4af7102c2
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: murmur
    databaseName: murmur_o49g
    user: murmur_o49g_user
    region: oregon
    plan: starter
    ipAllowList: [] # Render services only