services:
  - type: web
    name: blog-app
    runtime: ruby
    env: ruby
    region: oregon
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: blog-app-db
    databaseName: blog_app_production
    user: blog_app
    region: oregon
    plan: starter
    ipAllowList: [] # Render services only